name = "Free2Pee"
uuid = "73229e22-ef45-435f-bd3c-496030ea9f04"
authors = ["anand jain <anandj@uchicago.edu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONTables = "b9914132-a727-11e9-1322-f18e41205b0b"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"
